name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # WAJIB ADA: Biar GitHub bisa bikin token OIDC buat ngobrol sama GCP
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Test Auth (Cek siapa yang lagi login)
      run: gcloud auth list
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy dashboard-business-counter \
          --source . \
          --region asia-southeast2 \
          --project project-f643cc3e-cf6f-4622-865 \
          --allow-unauthenticated \
          --port 3000
